# Actividad Evaluable: Obtención de estadísticas descriptivas  
Cargar los datos y visualizar las primeras 5 filas:

In [159]:
import pandas as pd
import numpy as np

datos = pd.read_csv("avocado.csv")
print(datos.head())

   Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0           0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1           1  2015-12-20          1.35      54876.98   674.28   44638.81   
2           2  2015-12-13          0.93     118220.22   794.70  109149.67   
3           3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4           4  2015-11-29          1.28      51039.60   941.48   43838.39   

     4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0   48.16     8696.87     8603.62       93.25          0.0  conventional   
1   58.33     9505.56     9408.07       97.49          0.0  conventional   
2  130.50     8145.35     8042.21      103.14          0.0  conventional   
3   72.58     5811.16     5677.40      133.76          0.0  conventional   
4   75.78     6183.95     5986.26      197.69          0.0  conventional   

   year  region  
0  2015  Albany  
1  2015  Albany  
2  2015  Albany  
3  2015 

## Total de datos por categoría y en total:

In [160]:
total = datos.count()
print(total)
print("Total de datos: ", total.sum())

Unnamed: 0      18249
Date            18249
AveragePrice    18249
Total Volume    18249
4046            18249
4225            18249
4770            18249
Total Bags      18249
Small Bags      18249
Large Bags      18249
XLarge Bags     18249
type            18249
year            18249
region          18249
dtype: int64
Total de datos:  255486


## Variables: Analizar las variables para saber qué representan.

ID: Variable tipo int. No está marcado el nombre pero es el ID de la venta de un día en una determinada región.   
Date: Variable de tipo fecha. Es la fecha en la que se realizó determinada venta.  
AveragePrice: Variable de tipo float. El precio promedio del aguacate.  
TotalVolume: Variable de tipo float. El volumen total que se vendió.  
4046: Variable de tipo float. Variable mal nombrada, no se explica qué es.  
4225: Variable de tipo float. Variable mal nombrada, no se explica qué es.  
4770: Variable de tipo float. Variable mal nombrada, no se explica qué es.  
Total bags: Variable de tipo float. Dinero generado por el total de bolsas vendidas.  
Small Bags: Variable de tipo float. Dinero generado por las bolsas pequeñas vendidas.  
Large Bags: Variable de tipo float. Dinero generado por las bolsas grandes vendidas.  
XLarge Bags: Variable de tipo float. Dinero generado por las bolsas extra grandes vendidas.  
type: Variable de tipo string. Tipo de aguacate.  
year: Variable de tipo int. Año de la venta.  
region: Variable de tipo string. Región de la venta.  

Rangos de las variables:

In [161]:
# Date
print("Rango Date: ")
print(datos['Date'].min())
print(datos['Date'].max(), "\n")

# AveragePrice
print("Rango AveragePrice: ")
print(datos['AveragePrice'].min())
print(datos['AveragePrice'].max(), "\n")

# Total Volume
print("Rango Total Volume: ")
print(datos['Total Volume'].min())
print(datos['Total Volume'].max(), "\n")

# 4046
print("Rango 4046: ")
print(datos['4046'].min())
print(datos['4046'].max(), "\n")

# 4225
print("Rango 4225: ")
print(datos['4225'].min())
print(datos['4225'].max(), "\n")

# 4770
print("Rango 4770: ")
print(datos['4770'].min())
print(datos['4770'].max(), "\n")

# Total Bags
print("Rango Total Bags: ")
print(datos['Total Bags'].min())
print(datos['Total Bags'].max(), "\n")

# Small Bags
print("Rango Small Bags: ")
print(datos['Small Bags'].min())
print(datos['Small Bags'].max(), "\n")

# Large Bags
print("Rango Large Bags: ")
print(datos['Large Bags'].min())
print(datos['Large Bags'].max(), "\n")

# XLarge Bags
print("Rango XLarge Bags: ")
print(datos['XLarge Bags'].min())
print(datos['XLarge Bags'].max(), "\n")

# year
print("Rango year: ")
print(datos['year'].min())
print(datos['year'].max(), "\n")

Rango Date: 
2015-01-04
2018-03-25 

Rango AveragePrice: 
0.44
3.25 

Rango Total Volume: 
84.56
62505646.52 

Rango 4046: 
0.0
22743616.17 

Rango 4225: 
0.0
20470572.61 

Rango 4770: 
0.0
2546439.11 

Rango Total Bags: 
0.0
19373134.37 

Rango Small Bags: 
0.0
13384586.8 

Rango Large Bags: 
0.0
5719096.61 

Rango XLarge Bags: 
0.0
551693.65 

Rango year: 
2015
2018 



## Basándose en la media, mediana y desviación estándar de cada variable, ¿qué conclusiones pueden entregar los datos?

Para esto realicé una función que imprime la media, mediana y desviación estándar de la columna solicitada.

In [162]:
def media_mediana_desviacion_estandar(producto):
    media = round(np.mean(datos[producto]), 3)
    mediana = np.median(datos[producto])
    de = round(np.std(datos[producto]), 3)
    print(producto)
    print("Media:", media, "Mediana:", mediana, "Desviacion estandar:", de)



In [163]:
media_mediana_desviacion_estandar('AveragePrice')

AveragePrice
Media: 1.406 Mediana: 1.37 Desviacion estandar: 0.403


Conclusiones: como la mediana es menor que la media y tenemos muchos datos,
podemos deducir que tenemos más datos por debajo de la media que por encima,
entonces hay datos grandes que están inflando un poco la media. Además, la
desviación estándar nos indica que los datos no son demasiado dispersos, pero
tienen una variabilidad moderada.

In [164]:
media_mediana_desviacion_estandar('Total Volume')


Total Volume
Media: 850644.013 Mediana: 107376.76 Desviacion estandar: 3453450.731


Conclusiones: Como la mediana es mucho menor a la media, podemos suponer que la
gran mayoría de los datos son menores a la media, lo que significa que hay unos
cuantos datos muy grandes que inflan a la media. Además, la desviación estándar
es alrededor de 4 veces la media, por lo que podemos decir que los datos tienen
una gran variabilidad.

In [165]:
media_mediana_desviacion_estandar('4046')


4046
Media: 293008.425 Mediana: 8645.3 Desviacion estandar: 1264954.422


Conclusiones: Nuevamente tenemos una mediana mucho menor a la media, lo que indica
que tenemos muchos datos pequeños y pocos datos muy grandes. La desviación estándar
es muy grande, lo que indica que los datos tienen una gran variabilidad.

In [166]:
media_mediana_desviacion_estandar('4225')


4225
Media: 295154.568 Mediana: 29061.02 Desviacion estandar: 1204087.409


Conclusiones: Nuevamente tenemos una mediana mucho menor a la media, lo que indica
que tenemos muchos datos pequeños y pocos datos muy grandes. La desviación estándar
es muy grande, lo que indica que los datos tienen una gran variabilidad.

In [167]:
media_mediana_desviacion_estandar('4770')


4770
Media: 22839.736 Mediana: 184.99 Desviacion estandar: 107461.124


Conclusiones: Al igual que para las dos variables anteriores, la mediana es mucho
menor a la media, entonces la mayoría de los datos son pequeños y hay pocos datos muy grandes.
Además, la desviación estándar es bastante grande, así que hay gran variabilidad en los datos.

In [168]:
media_mediana_desviacion_estandar('Total Bags')


Total Bags
Media: 239639.202 Mediana: 39743.83 Desviacion estandar: 986215.377


Conclusiones: Nuevamente tenemos una mediana mucho menor a la media, lo que indica
que tenemos muchos datos pequeños y pocos datos muy grandes. La desviación estándar
es muy grande, lo que indica que los datos tienen una gran variabilidad.

In [169]:
media_mediana_desviacion_estandar('Small Bags')


Small Bags
Media: 182194.687 Mediana: 26362.82 Desviacion estandar: 746158.07


Conclusiones: Nuevamente tenemos una mediana mucho menor a la media, lo que indica
que tenemos muchos datos pequeños y pocos datos muy grandes. La desviación estándar
es muy grande, lo que indica que los datos tienen una gran variabilidad.

In [170]:
media_mediana_desviacion_estandar('Large Bags')


Large Bags
Media: 54338.088 Mediana: 2647.71 Desviacion estandar: 243959.28


Conclusiones: Nuevamente tenemos una mediana mucho menor a la media, lo que indica
que tenemos muchos datos pequeños y pocos datos muy grandes. La desviación estándar
es muy grande, lo que indica que los datos tienen una gran variabilidad.

In [171]:
media_mediana_desviacion_estandar('XLarge Bags')


XLarge Bags
Media: 3106.427 Mediana: 0.0 Desviacion estandar: 17692.41


Conclusiones: Este caso es muy interesante, ya que la mediana es cero. Esto indica que la mayoría de los datos son 0. Tenemos que la desviación estándar es casi 6 veces la media.
Esto es interesante porque como la mediana es 0, entonces hay números mucho más grandes
que la media para esta variable.

In [172]:
media_mediana_desviacion_estandar('year')


year
Media: 2016.148 Mediana: 2016.0 Desviacion estandar: 0.94


Conclusiones: Este caso tiene una media y una mediana muy similares, además de que la desviación
estándar es muy baja. Esto era de esperarse porque tenemos solamente 4 posibles datos:
2015, 2016, 2017 y 2018.

## Conclusiones generales:
La mayoría de las columnas tienen muchos datos pequeños que no se alejan tanto de la media y muchos datos grandes que llegan a alejarse bastante de la media. Hay unas cuantas columnas en las que la media y la mediana son muy cercanas y estas en su mayoría tienen una desviación estándar mucho más baja.
Para todos los datos no numéricos no es posible sacar media, mediana y desviación estándar.